services:
  - type: web
    name: cardiosonic-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 1 -b 0.0.0.0:$PORT app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.6
      - key: PORT
        value: 5001
